package com.chillax.dto;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressid
     *
     * @mbg.generated
     */
    private Integer addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressflag
     *
     * @mbg.generated
     */
    private String addressflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressname
     *
     * @mbg.generated
     */
    private String addressname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.wxid
     *
     * @mbg.generated
     */
    private String wxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressdefault
     *
     * @mbg.generated
     */
    private String addressdefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.customername
     *
     * @mbg.generated
     */
    private String customername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressid
     *
     * @return the value of address.addressid
     *
     * @mbg.generated
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressid
     *
     * @param addressid the value for address.addressid
     *
     * @mbg.generated
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressflag
     *
     * @return the value of address.addressflag
     *
     * @mbg.generated
     */
    public String getAddressflag() {
        return addressflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressflag
     *
     * @param addressflag the value for address.addressflag
     *
     * @mbg.generated
     */
    public void setAddressflag(String addressflag) {
        this.addressflag = addressflag == null ? null : addressflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressname
     *
     * @return the value of address.addressname
     *
     * @mbg.generated
     */
    public String getAddressname() {
        return addressname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressname
     *
     * @param addressname the value for address.addressname
     *
     * @mbg.generated
     */
    public void setAddressname(String addressname) {
        this.addressname = addressname == null ? null : addressname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.wxid
     *
     * @return the value of address.wxid
     *
     * @mbg.generated
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.wxid
     *
     * @param wxid the value for address.wxid
     *
     * @mbg.generated
     */
    public void setWxid(String wxid) {
        this.wxid = wxid == null ? null : wxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressdefault
     *
     * @return the value of address.addressdefault
     *
     * @mbg.generated
     */
    public String getAddressdefault() {
        return addressdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressdefault
     *
     * @param addressdefault the value for address.addressdefault
     *
     * @mbg.generated
     */
    public void setAddressdefault(String addressdefault) {
        this.addressdefault = addressdefault == null ? null : addressdefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.sex
     *
     * @return the value of address.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.sex
     *
     * @param sex the value for address.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.customername
     *
     * @return the value of address.customername
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.customername
     *
     * @param customername the value for address.customername
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }
}