package com.chillax.dto;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.wxid
     *
     * @mbg.generated
     */
    private String wxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customername
     *
     * @mbg.generated
     */
    private String customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customertel
     *
     * @mbg.generated
     */
    private String customertel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customerplace
     *
     * @mbg.generated
     */
    private String customerplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customerflag
     *
     * @mbg.generated
     */
    private Integer customerflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.wxid
     *
     * @return the value of customer.wxid
     *
     * @mbg.generated
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.wxid
     *
     * @param wxid the value for customer.wxid
     *
     * @mbg.generated
     */
    public void setWxid(String wxid) {
        this.wxid = wxid == null ? null : wxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customername
     *
     * @return the value of customer.customername
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customername
     *
     * @param customername the value for customer.customername
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customertel
     *
     * @return the value of customer.customertel
     *
     * @mbg.generated
     */
    public String getCustomertel() {
        return customertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customertel
     *
     * @param customertel the value for customer.customertel
     *
     * @mbg.generated
     */
    public void setCustomertel(String customertel) {
        this.customertel = customertel == null ? null : customertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customerplace
     *
     * @return the value of customer.customerplace
     *
     * @mbg.generated
     */
    public String getCustomerplace() {
        return customerplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customerplace
     *
     * @param customerplace the value for customer.customerplace
     *
     * @mbg.generated
     */
    public void setCustomerplace(String customerplace) {
        this.customerplace = customerplace == null ? null : customerplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customerflag
     *
     * @return the value of customer.customerflag
     *
     * @mbg.generated
     */
    public Integer getCustomerflag() {
        return customerflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customerflag
     *
     * @param customerflag the value for customer.customerflag
     *
     * @mbg.generated
     */
    public void setCustomerflag(Integer customerflag) {
        this.customerflag = customerflag;
    }
}