package com.chillax.dto;

public class Goodtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.goodtypeid
     *
     * @mbg.generated
     */
    private String goodtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.goodtypename
     *
     * @mbg.generated
     */
    private String goodtypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.includegood
     *
     * @mbg.generated
     */
    private String includegood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.goodtypeflag
     *
     * @mbg.generated
     */
    private Integer goodtypeflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.id
     *
     * @return the value of goodtype.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.id
     *
     * @param id the value for goodtype.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.goodtypeid
     *
     * @return the value of goodtype.goodtypeid
     *
     * @mbg.generated
     */
    public String getGoodtypeid() {
        return goodtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.goodtypeid
     *
     * @param goodtypeid the value for goodtype.goodtypeid
     *
     * @mbg.generated
     */
    public void setGoodtypeid(String goodtypeid) {
        this.goodtypeid = goodtypeid == null ? null : goodtypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.goodtypename
     *
     * @return the value of goodtype.goodtypename
     *
     * @mbg.generated
     */
    public String getGoodtypename() {
        return goodtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.goodtypename
     *
     * @param goodtypename the value for goodtype.goodtypename
     *
     * @mbg.generated
     */
    public void setGoodtypename(String goodtypename) {
        this.goodtypename = goodtypename == null ? null : goodtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.includegood
     *
     * @return the value of goodtype.includegood
     *
     * @mbg.generated
     */
    public String getIncludegood() {
        return includegood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.includegood
     *
     * @param includegood the value for goodtype.includegood
     *
     * @mbg.generated
     */
    public void setIncludegood(String includegood) {
        this.includegood = includegood == null ? null : includegood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.goodtypeflag
     *
     * @return the value of goodtype.goodtypeflag
     *
     * @mbg.generated
     */
    public Integer getGoodtypeflag() {
        return goodtypeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.goodtypeflag
     *
     * @param goodtypeflag the value for goodtype.goodtypeflag
     *
     * @mbg.generated
     */
    public void setGoodtypeflag(Integer goodtypeflag) {
        this.goodtypeflag = goodtypeflag;
    }
}