package com.chillax.dto;

public class Goodandshop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodandshop.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodandshop.tbShopId
     *
     * @mbg.generated
     */
    private Integer tbshopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodandshop.tbGoodId
     *
     * @mbg.generated
     */
    private Integer tbgoodid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodandshop.id
     *
     * @return the value of goodandshop.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodandshop.id
     *
     * @param id the value for goodandshop.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodandshop.tbShopId
     *
     * @return the value of goodandshop.tbShopId
     *
     * @mbg.generated
     */
    public Integer getTbshopid() {
        return tbshopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodandshop.tbShopId
     *
     * @param tbshopid the value for goodandshop.tbShopId
     *
     * @mbg.generated
     */
    public void setTbshopid(Integer tbshopid) {
        this.tbshopid = tbshopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodandshop.tbGoodId
     *
     * @return the value of goodandshop.tbGoodId
     *
     * @mbg.generated
     */
    public Integer getTbgoodid() {
        return tbgoodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodandshop.tbGoodId
     *
     * @param tbgoodid the value for goodandshop.tbGoodId
     *
     * @mbg.generated
     */
    public void setTbgoodid(Integer tbgoodid) {
        this.tbgoodid = tbgoodid;
    }
}