package com.chillax.dto;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.wxid
     *
     * @mbg.generated
     */
    private String wxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderflag
     *
     * @mbg.generated
     */
    private Integer orderflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderdetailid
     *
     * @mbg.generated
     */
    private Long orderdetailid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.wxid
     *
     * @return the value of order.wxid
     *
     * @mbg.generated
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.wxid
     *
     * @param wxid the value for order.wxid
     *
     * @mbg.generated
     */
    public void setWxid(String wxid) {
        this.wxid = wxid == null ? null : wxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderflag
     *
     * @return the value of order.orderflag
     *
     * @mbg.generated
     */
    public Integer getOrderflag() {
        return orderflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderflag
     *
     * @param orderflag the value for order.orderflag
     *
     * @mbg.generated
     */
    public void setOrderflag(Integer orderflag) {
        this.orderflag = orderflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderdetailid
     *
     * @return the value of order.orderdetailid
     *
     * @mbg.generated
     */
    public Long getOrderdetailid() {
        return orderdetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderdetailid
     *
     * @param orderdetailid the value for order.orderdetailid
     *
     * @mbg.generated
     */
    public void setOrderdetailid(Long orderdetailid) {
        this.orderdetailid = orderdetailid;
    }
}