package com.chillax.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderdetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public OrderdetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidIsNull() {
            addCriterion("orderdetailid is null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidIsNotNull() {
            addCriterion("orderdetailid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidEqualTo(Long value) {
            addCriterion("orderdetailid =", value, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidNotEqualTo(Long value) {
            addCriterion("orderdetailid <>", value, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidGreaterThan(Long value) {
            addCriterion("orderdetailid >", value, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidGreaterThanOrEqualTo(Long value) {
            addCriterion("orderdetailid >=", value, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidLessThan(Long value) {
            addCriterion("orderdetailid <", value, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidLessThanOrEqualTo(Long value) {
            addCriterion("orderdetailid <=", value, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidIn(List<Long> values) {
            addCriterion("orderdetailid in", values, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidNotIn(List<Long> values) {
            addCriterion("orderdetailid not in", values, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidBetween(Long value1, Long value2) {
            addCriterion("orderdetailid between", value1, value2, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailidNotBetween(Long value1, Long value2) {
            addCriterion("orderdetailid not between", value1, value2, "orderdetailid");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumIsNull() {
            addCriterion("orderdetailsum is null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumIsNotNull() {
            addCriterion("orderdetailsum is not null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumEqualTo(BigDecimal value) {
            addCriterion("orderdetailsum =", value, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumNotEqualTo(BigDecimal value) {
            addCriterion("orderdetailsum <>", value, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumGreaterThan(BigDecimal value) {
            addCriterion("orderdetailsum >", value, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("orderdetailsum >=", value, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumLessThan(BigDecimal value) {
            addCriterion("orderdetailsum <", value, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("orderdetailsum <=", value, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumIn(List<BigDecimal> values) {
            addCriterion("orderdetailsum in", values, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumNotIn(List<BigDecimal> values) {
            addCriterion("orderdetailsum not in", values, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orderdetailsum between", value1, value2, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailsumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orderdetailsum not between", value1, value2, "orderdetailsum");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentIsNull() {
            addCriterion("orderdetailcontent is null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentIsNotNull() {
            addCriterion("orderdetailcontent is not null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentEqualTo(String value) {
            addCriterion("orderdetailcontent =", value, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentNotEqualTo(String value) {
            addCriterion("orderdetailcontent <>", value, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentGreaterThan(String value) {
            addCriterion("orderdetailcontent >", value, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentGreaterThanOrEqualTo(String value) {
            addCriterion("orderdetailcontent >=", value, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentLessThan(String value) {
            addCriterion("orderdetailcontent <", value, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentLessThanOrEqualTo(String value) {
            addCriterion("orderdetailcontent <=", value, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentLike(String value) {
            addCriterion("orderdetailcontent like", value, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentNotLike(String value) {
            addCriterion("orderdetailcontent not like", value, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentIn(List<String> values) {
            addCriterion("orderdetailcontent in", values, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentNotIn(List<String> values) {
            addCriterion("orderdetailcontent not in", values, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentBetween(String value1, String value2) {
            addCriterion("orderdetailcontent between", value1, value2, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailcontentNotBetween(String value1, String value2) {
            addCriterion("orderdetailcontent not between", value1, value2, "orderdetailcontent");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagIsNull() {
            addCriterion("orderdetailflag is null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagIsNotNull() {
            addCriterion("orderdetailflag is not null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagEqualTo(Integer value) {
            addCriterion("orderdetailflag =", value, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagNotEqualTo(Integer value) {
            addCriterion("orderdetailflag <>", value, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagGreaterThan(Integer value) {
            addCriterion("orderdetailflag >", value, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderdetailflag >=", value, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagLessThan(Integer value) {
            addCriterion("orderdetailflag <", value, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagLessThanOrEqualTo(Integer value) {
            addCriterion("orderdetailflag <=", value, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagIn(List<Integer> values) {
            addCriterion("orderdetailflag in", values, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagNotIn(List<Integer> values) {
            addCriterion("orderdetailflag not in", values, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagBetween(Integer value1, Integer value2) {
            addCriterion("orderdetailflag between", value1, value2, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andOrderdetailflagNotBetween(Integer value1, Integer value2) {
            addCriterion("orderdetailflag not between", value1, value2, "orderdetailflag");
            return (Criteria) this;
        }

        public Criteria andWxidIsNull() {
            addCriterion("wxid is null");
            return (Criteria) this;
        }

        public Criteria andWxidIsNotNull() {
            addCriterion("wxid is not null");
            return (Criteria) this;
        }

        public Criteria andWxidEqualTo(String value) {
            addCriterion("wxid =", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidNotEqualTo(String value) {
            addCriterion("wxid <>", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidGreaterThan(String value) {
            addCriterion("wxid >", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidGreaterThanOrEqualTo(String value) {
            addCriterion("wxid >=", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidLessThan(String value) {
            addCriterion("wxid <", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidLessThanOrEqualTo(String value) {
            addCriterion("wxid <=", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidLike(String value) {
            addCriterion("wxid like", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidNotLike(String value) {
            addCriterion("wxid not like", value, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidIn(List<String> values) {
            addCriterion("wxid in", values, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidNotIn(List<String> values) {
            addCriterion("wxid not in", values, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidBetween(String value1, String value2) {
            addCriterion("wxid between", value1, value2, "wxid");
            return (Criteria) this;
        }

        public Criteria andWxidNotBetween(String value1, String value2) {
            addCriterion("wxid not between", value1, value2, "wxid");
            return (Criteria) this;
        }

        public Criteria andShopnameIsNull() {
            addCriterion("shopname is null");
            return (Criteria) this;
        }

        public Criteria andShopnameIsNotNull() {
            addCriterion("shopname is not null");
            return (Criteria) this;
        }

        public Criteria andShopnameEqualTo(String value) {
            addCriterion("shopname =", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotEqualTo(String value) {
            addCriterion("shopname <>", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameGreaterThan(String value) {
            addCriterion("shopname >", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameGreaterThanOrEqualTo(String value) {
            addCriterion("shopname >=", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameLessThan(String value) {
            addCriterion("shopname <", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameLessThanOrEqualTo(String value) {
            addCriterion("shopname <=", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameLike(String value) {
            addCriterion("shopname like", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotLike(String value) {
            addCriterion("shopname not like", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameIn(List<String> values) {
            addCriterion("shopname in", values, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotIn(List<String> values) {
            addCriterion("shopname not in", values, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameBetween(String value1, String value2) {
            addCriterion("shopname between", value1, value2, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotBetween(String value1, String value2) {
            addCriterion("shopname not between", value1, value2, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopphoneIsNull() {
            addCriterion("shopphone is null");
            return (Criteria) this;
        }

        public Criteria andShopphoneIsNotNull() {
            addCriterion("shopphone is not null");
            return (Criteria) this;
        }

        public Criteria andShopphoneEqualTo(String value) {
            addCriterion("shopphone =", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneNotEqualTo(String value) {
            addCriterion("shopphone <>", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneGreaterThan(String value) {
            addCriterion("shopphone >", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneGreaterThanOrEqualTo(String value) {
            addCriterion("shopphone >=", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneLessThan(String value) {
            addCriterion("shopphone <", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneLessThanOrEqualTo(String value) {
            addCriterion("shopphone <=", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneLike(String value) {
            addCriterion("shopphone like", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneNotLike(String value) {
            addCriterion("shopphone not like", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneIn(List<String> values) {
            addCriterion("shopphone in", values, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneNotIn(List<String> values) {
            addCriterion("shopphone not in", values, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneBetween(String value1, String value2) {
            addCriterion("shopphone between", value1, value2, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneNotBetween(String value1, String value2) {
            addCriterion("shopphone not between", value1, value2, "shopphone");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateIsNull() {
            addCriterion("orderdetailstate is null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateIsNotNull() {
            addCriterion("orderdetailstate is not null");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateEqualTo(String value) {
            addCriterion("orderdetailstate =", value, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateNotEqualTo(String value) {
            addCriterion("orderdetailstate <>", value, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateGreaterThan(String value) {
            addCriterion("orderdetailstate >", value, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateGreaterThanOrEqualTo(String value) {
            addCriterion("orderdetailstate >=", value, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateLessThan(String value) {
            addCriterion("orderdetailstate <", value, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateLessThanOrEqualTo(String value) {
            addCriterion("orderdetailstate <=", value, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateLike(String value) {
            addCriterion("orderdetailstate like", value, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateNotLike(String value) {
            addCriterion("orderdetailstate not like", value, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateIn(List<String> values) {
            addCriterion("orderdetailstate in", values, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateNotIn(List<String> values) {
            addCriterion("orderdetailstate not in", values, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateBetween(String value1, String value2) {
            addCriterion("orderdetailstate between", value1, value2, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrderdetailstateNotBetween(String value1, String value2) {
            addCriterion("orderdetailstate not between", value1, value2, "orderdetailstate");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNull() {
            addCriterion("ordertime is null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNotNull() {
            addCriterion("ordertime is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeEqualTo(Date value) {
            addCriterion("ordertime =", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotEqualTo(Date value) {
            addCriterion("ordertime <>", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThan(Date value) {
            addCriterion("ordertime >", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ordertime >=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThan(Date value) {
            addCriterion("ordertime <", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThanOrEqualTo(Date value) {
            addCriterion("ordertime <=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIn(List<Date> values) {
            addCriterion("ordertime in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotIn(List<Date> values) {
            addCriterion("ordertime not in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeBetween(Date value1, Date value2) {
            addCriterion("ordertime between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotBetween(Date value1, Date value2) {
            addCriterion("ordertime not between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNull() {
            addCriterion("addressid is null");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNotNull() {
            addCriterion("addressid is not null");
            return (Criteria) this;
        }

        public Criteria andAddressidEqualTo(Integer value) {
            addCriterion("addressid =", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotEqualTo(Integer value) {
            addCriterion("addressid <>", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThan(Integer value) {
            addCriterion("addressid >", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThanOrEqualTo(Integer value) {
            addCriterion("addressid >=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThan(Integer value) {
            addCriterion("addressid <", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThanOrEqualTo(Integer value) {
            addCriterion("addressid <=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidIn(List<Integer> values) {
            addCriterion("addressid in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotIn(List<Integer> values) {
            addCriterion("addressid not in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidBetween(Integer value1, Integer value2) {
            addCriterion("addressid between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotBetween(Integer value1, Integer value2) {
            addCriterion("addressid not between", value1, value2, "addressid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderdetail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderdetail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}