package com.chillax.dto;

import java.util.List;

public class Shops {
	/*ÐÂÔö*/
	private List<Goods> goodsList;
	
    public List<Goods> getGoodsList() {
		return goodsList;
	}

	public void setGoodsList(List<Goods> goodsList) {
		this.goodsList = goodsList;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shopid
     *
     * @mbg.generated
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.distance
     *
     * @mbg.generated
     */
    private Double distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.sales
     *
     * @mbg.generated
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.activity
     *
     * @mbg.generated
     */
    private String activity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shopflag
     *
     * @mbg.generated
     */
    private Integer shopflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.place
     *
     * @mbg.generated
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.firsteat
     *
     * @mbg.generated
     */
    private String firsteat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.discount
     *
     * @mbg.generated
     */
    private String discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.cutprice
     *
     * @mbg.generated
     */
    private String cutprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.wait
     *
     * @mbg.generated
     */
    private Integer wait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.startprice
     *
     * @mbg.generated
     */
    private Integer startprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.expressprice
     *
     * @mbg.generated
     */
    private Integer expressprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.id
     *
     * @return the value of shops.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.id
     *
     * @param id the value for shops.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shopid
     *
     * @return the value of shops.shopid
     *
     * @mbg.generated
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shopid
     *
     * @param shopid the value for shops.shopid
     *
     * @mbg.generated
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.distance
     *
     * @return the value of shops.distance
     *
     * @mbg.generated
     */
    public Double getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.distance
     *
     * @param distance the value for shops.distance
     *
     * @mbg.generated
     */
    public void setDistance(Double distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.sales
     *
     * @return the value of shops.sales
     *
     * @mbg.generated
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.sales
     *
     * @param sales the value for shops.sales
     *
     * @mbg.generated
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.logo
     *
     * @return the value of shops.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.logo
     *
     * @param logo the value for shops.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.name
     *
     * @return the value of shops.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.name
     *
     * @param name the value for shops.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.activity
     *
     * @return the value of shops.activity
     *
     * @mbg.generated
     */
    public String getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.activity
     *
     * @param activity the value for shops.activity
     *
     * @mbg.generated
     */
    public void setActivity(String activity) {
        this.activity = activity == null ? null : activity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shopflag
     *
     * @return the value of shops.shopflag
     *
     * @mbg.generated
     */
    public Integer getShopflag() {
        return shopflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shopflag
     *
     * @param shopflag the value for shops.shopflag
     *
     * @mbg.generated
     */
    public void setShopflag(Integer shopflag) {
        this.shopflag = shopflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.place
     *
     * @return the value of shops.place
     *
     * @mbg.generated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.place
     *
     * @param place the value for shops.place
     *
     * @mbg.generated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.tel
     *
     * @return the value of shops.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.tel
     *
     * @param tel the value for shops.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.firsteat
     *
     * @return the value of shops.firsteat
     *
     * @mbg.generated
     */
    public String getFirsteat() {
        return firsteat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.firsteat
     *
     * @param firsteat the value for shops.firsteat
     *
     * @mbg.generated
     */
    public void setFirsteat(String firsteat) {
        this.firsteat = firsteat == null ? null : firsteat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.discount
     *
     * @return the value of shops.discount
     *
     * @mbg.generated
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.discount
     *
     * @param discount the value for shops.discount
     *
     * @mbg.generated
     */
    public void setDiscount(String discount) {
        this.discount = discount == null ? null : discount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.cutprice
     *
     * @return the value of shops.cutprice
     *
     * @mbg.generated
     */
    public String getCutprice() {
        return cutprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.cutprice
     *
     * @param cutprice the value for shops.cutprice
     *
     * @mbg.generated
     */
    public void setCutprice(String cutprice) {
        this.cutprice = cutprice == null ? null : cutprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.wait
     *
     * @return the value of shops.wait
     *
     * @mbg.generated
     */
    public Integer getWait() {
        return wait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.wait
     *
     * @param wait the value for shops.wait
     *
     * @mbg.generated
     */
    public void setWait(Integer wait) {
        this.wait = wait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.startprice
     *
     * @return the value of shops.startprice
     *
     * @mbg.generated
     */
    public Integer getStartprice() {
        return startprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.startprice
     *
     * @param startprice the value for shops.startprice
     *
     * @mbg.generated
     */
    public void setStartprice(Integer startprice) {
        this.startprice = startprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.expressprice
     *
     * @return the value of shops.expressprice
     *
     * @mbg.generated
     */
    public Integer getExpressprice() {
        return expressprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.expressprice
     *
     * @param expressprice the value for shops.expressprice
     *
     * @mbg.generated
     */
    public void setExpressprice(Integer expressprice) {
        this.expressprice = expressprice;
    }
}