package com.chillax.mapper;

import com.chillax.dto.Goodandshop;
import com.chillax.dto.GoodandshopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodandshopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    long countByExample(GoodandshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    int deleteByExample(GoodandshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    int insert(Goodandshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    int insertSelective(Goodandshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    List<Goodandshop> selectByExample(GoodandshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    Goodandshop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Goodandshop record, @Param("example") GoodandshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Goodandshop record, @Param("example") GoodandshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Goodandshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodandshop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Goodandshop record);
}