package com.chillax.mapper;

import com.chillax.dto.Goodtype;
import com.chillax.dto.GoodtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    long countByExample(GoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    int deleteByExample(GoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    int insert(Goodtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    int insertSelective(Goodtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    List<Goodtype> selectByExample(GoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    Goodtype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Goodtype record, @Param("example") GoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Goodtype record, @Param("example") GoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Goodtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Goodtype record);
}